name: docker pr

on:
  push:
    branches-ignore:
      - "main"

env:
  IMAGE_FQDN: ghcr.io/eugenmayer/jodconverter

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push base
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: jodconverter-base
          tags: | 
            ${{ env.IMAGE_FQDN }}:base
      - name: Build and push gui
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: jodconverter-gui
          tags: |
            ${{ env.IMAGE_FQDN }}:gui
      - name: Build and push rest
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: jodconverter-rest
          tags: |
            ${{ env.IMAGE_FQDN }}:rest
